## This role is responsible for deploying the Data Manager Service for dojot
# TODO: Aggregate where necessary and add retries

- name: dojot - Data Manager service
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'data_manager_service.yaml.j2') | from_yaml }}"

- name: dojot - Data Manager deployment
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'data_manager_deployment.yaml.j2') | from_yaml }}"
