---
# TODO: Set tags
# TODO: Check what variables should be defined on inventory

# The group k8s-endpoint refer to the nodes that have access to the kubernetes api
# Its is possible to run from localhost accessing a remote node by defining a kubeconfig file
- hosts: dojot-k8s[0]
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: k8s-api-bootstrap
    - role: dojot-basic # Create the base for deploying dojot

# Deploy ZK to the environment
# TODO: Add possibility of using an external zk by setting config variables
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  roles:
    - role: zookeeper

# Deploy postgreSQL to the environment
# TODO: Add possibility of using an external postgres by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  roles:
    - role: databases/postgresql

# Deploy mongoDB to the environment
# TODO: Add possibility of using an external mongodb by setting DB config variables
# TODO: Support a HA cluster
- hosts: dojot-k8s[0]
  any_errors_fatal: true
  roles:
    - role: databases/mongodb



# TODO: Configure NGinx for https gui
# TODO: Add history service
# TODO: Add persister service
# TODO: Add iotagent-mosca with its redis
# TODO: Add GUI service
# TODO: Add the data-broker service with redis
# TODO: Add device-manager with redis
# TODO: Add auth service with redis
# TODO: Add kong as apigw, run kong-migrations and configure routes
# TODO: Add flowbroker service with redis and context-manager
# TODO: Adds rabbitmq
# TODO: Adds kafka
