## This role is responsible for deploying the GUI Service for dojot
# TODO: Aggregate where necessary and add retries

- name: dojot - GUI service
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'gui_service.yaml.j2') | from_yaml }}"

- name: dojot - GUI deployment
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'gui_deployment.yaml.j2') | from_yaml }}"
