## This role is responsible for deploying postgreSQL for dojot
# TODO: Aggregate where necessary and add retries

- name: dojot - PostgreSQL secrets
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'postgres_secret.yaml.j2') | from_yaml }}"

- name: dojot - PostgreSQL service
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'postgres_service.yaml.j2') | from_yaml }}"

- name: dojot - PostgreSQL Persistent Volume Claim
  when: dojot_psql_persistent_volumes
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'postgres_pvc.yaml.j2') | from_yaml }}"

- name: dojot - PostgreSQL Init Config Map
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'postgres_init_config_map.yaml.j2') | from_yaml }}"

- name: dojot - PostgreSQL deployment
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'postgres_deployment.yaml.j2') | from_yaml }}"
