## This role is responsible for deploying the Auth Service for dojot
# TODO: Aggregate where necessary and add retries

- name: dojot - Auth service
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'auth_service.yaml.j2') | from_yaml }}"

- name: dojot - Auth secrets
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'auth_secrets.yaml.j2') | from_yaml }}"

- name: dojot - Auth Deployment
  k8s:
    kubeconfig: "{{ dojot_kubeconfig_file_path }}"
    state: present
    definition: "{{ lookup('template', 'auth_deployment.yaml.j2') | from_yaml }}"
