---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: postgres
    app: dojot
  name: postgres
  namespace: "{{ dojot_namespace }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
        app: dojot
    spec:
      containers:
      - image: "postgres:{{ dojot_psql_version }}"
        name: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_DB
            value: "{{ dojot_psql_default_db }}"
      restartPolicy: Always
      # TODO: Default mountpoint set by PGDATA: /var/lib/postgresql/data
      # TODO: Mount postgres db init file
      # TODO: View deploy strategies
