---
all:
  hosts:
    localhost:
        ansible_connection: local
        ansible_python.version.major: 3
    master_node:
      ansible_host: MASTER_NODE_ADDRESS
    worker_node:
      ansible_host: WORKER_NODE_ADDRESS

  children:
    dojot-k8s:
      hosts:
        localhost:
    k8s-nodes:
      children:
        master_nodes:
          hosts:
            master_node:
        worker_nodes:
          hosts:
            worker_node:
