---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    name: zookeeper
    app: dojot
  name: zookeeper
  namespace: "{{ dojot_namespace }}"
spec:
  selector:
    matchLabels:
      app: dojot
      name: zookeeper
  serviceName: zookeeper-cluster
  replicas: 1
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  template:
    metadata:
      namespace: dojot
      labels:
        app: dojot
        name: zookeeper
    spec:
      terminationGracePeriodSeconds: 1200
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           - topologyKey: "kubernetes.io/hostname"
             labelSelector:
               matchLabels:
                 name: zookeeper
                 app: dojot
      containers:
        - name: zookeeper
          ## - https://github.com/kubernetes/contrib/tree/master/statefulsets/zookeeper
          image: "gcr.io/google_samples/k8szk:v3"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -xec
            - zkGenConfig.sh && exec zkServer.sh start-foreground
          # TODO: Configure this ports
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          livenessProbe:
            exec:
              command:
                - zkOk.sh
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
                - zkOk.sh
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 6
            successThreshold: 1
          env:
            # TODO: Configure ports and other parameters
            # TODO: ZK replicas mustbe matched with replicas of the statefulset up there /\
            - name: ZK_REPLICAS
              value: "1"
            - name: ZK_CLIENT_PORT
              value: "2181"
            - name: ZK_ELECTION_PORT
              value: "3888"
            - name: ZK_SERVER_PORT
              value: "2888"
            - name: ZK_HEAP_SIZE
              value: "2G"
            - name: ZK_INIT_LIMIT
              value: "5"
            - name: ZK_LOG_LEVEL
              value: "INFO"
            - name: ZK_MAX_CLIENT_CNXNS
              value: "100"
            - name: ZK_MAX_SESSION_TIMEOUT
              value: "40000"
            - name: ZK_MIN_SESSION_TIMEOUT
              value: "4000"
            - name: ZK_PURGE_INTERVAL
              value: "0"
            - name: ZK_SNAP_RETAIN_COUNT
              value: "3"
            - name: ZK_SYNC_LIMIT
              value: "10"
            - name: ZK_TICK_TIME
              value: "2000"

      # TODO: Default mountpoint set: /var/lib/zookeeper
      # TODO: Add persistent volumes
      # TODO: Check if secrets are required, kafka secret, zk secret
