# Set the dojot deployment namesapce
dojot_namespace: dojot

dojot_version: 0.3.0-nightly20181227

dojot_domain_name: dojot.example.com

# Set kubernetes RBAC
dojot_kubernetes_rbac: true

# Set dojot configurations for Zookeeper
dojot_zk_persistent_volumes: false

# Set dojot configuration for postgreSQL
dojot_psql_persistent_volumes: false

# Set dojot configuration for mongoDB
dojot_mongodb_persistent_volumes: false

# Set Kafka configuration for dojot
dojot_kafka_persistent_volumes: false

# Set auth configuration
dojot_auth_email_enabled: false
